#!/usr/bin/env ruby
#
# Parses verbs in "pt_1000verbs.csv" and uploads them to google firebase
#
# requires ruby 2.5+ and bundler
# To use:
# 1. bundle install in this directory
# 2. put google firebase credentials in ./firebase_credentials/privatekey.json
# 3. Create an empty "verbs" collection in google firebase
# 4. Execute this file

require 'csv'
require 'json'
require 'google/cloud/firestore'

data = []
CSV.foreach("pt_1000verbs.csv", { encoding: "UTF-8", col_sep: ";" }) { |row| data << row }

# First row is the headers and includes the tense
current_header = "verb"
header_map = {}
data[0].each_with_index do |header, i|
  current_header = header unless header.nil?
  header_map[i] = current_header
end

# Second row is the person
person_headers = data[1]

all_verbs = []

data[2..-1].each_with_index do |row, i|
  verb = {}
  verb["rank"] = i + 1
  verb["conjugations"] = {}

  row.each_with_index do |cell, i|
    header = header_map[i]
    person = person_headers[i]

    case header
    when "verb"
      verb["verb"] = cell
    when "preposition"
      next
    when "Example"
      verb["example"] = cell
    when "regular/irregular"
      verb["regular"] = cell == "R"
    when "Gerúndio"
      verb["conjugations"]["gerúndio"] = cell
    when "Particípio passado"
      verb["conjugations"]["particípio passado"] = cell
    else
      verb["conjugations"][header] = {} unless verb["conjugations"].has_key? header
      verb["conjugations"][header][person] = cell
    end
  end
  all_verbs << verb
end

# write to JSON
File.open("parsed_verbs.json","w") do |f|
  f.write(JSON.pretty_generate(all_verbs))
end

# Upload to google firestore
keyfile = "firebase_credentials/privatekey.json"
creds = Google::Cloud::Firestore::Credentials.new keyfile
firestore = Google::Cloud::Firestore.new project_id: "conjugation-practice", credentials: creds

verb_collection = firestore.collection "verbs"
conjugation_collection = firestore.collection "conjugation"
list_collection = firestore.collection "lists"

# Store all verb names in an array for easy querying
all_verb_names = all_verbs.map { |v| v["verb"] };
list_collection.doc("verbs").set(all: all_verb_names)

# Store verb details and conjugations
all_verbs.each do |verb|
  verb_collection.doc(verb["verb"]).set(verb.slice("verb", "rank", "example", "regular"))
  conjugation_collection.doc(verb["verb"]).set(verb.slice("conjugations"))
end
